language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-simple-project' ]; then cd .. && eval "mv $currentfolder generator-simple-project" && cd generator-simple-project; fi
  - npm install -g bower
